// Mocks generated by Mockito 5.2.0 from annotations
// in flutter_tv_shows/test/blocs/logged_in_user_cubit/logged_in_user_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutter_tv_shows/data/models/login_user_request.dart' as _i5;
import 'package:flutter_tv_shows/data/models/user.dart' as _i2;
import 'package:flutter_tv_shows/data/repositories/auth_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeUser_0 extends _i1.Fake implements _i2.User {}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.User> loginUser(_i5.LoginUserRequest? loginUserRequest) =>
      (super.noSuchMethod(Invocation.method(#loginUser, [loginUserRequest]),
              returnValue: Future<_i2.User>.value(_FakeUser_0()))
          as _i4.Future<_i2.User>);
  @override
  _i4.Future<void> saveStringToSecuredHelper(String? key, String? value) =>
      (super.noSuchMethod(
          Invocation.method(#saveStringToSecuredHelper, [key, value]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<String?> getStringFromSecuredHelper(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringFromSecuredHelper, [key]),
          returnValue: Future<String?>.value()) as _i4.Future<String?>);
}
