// Mocks generated by Mockito 5.2.0 from annotations
// in flutter_tv_shows/test/blocs/movies_list_cubit/movies_list_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutter_tv_shows/data/models/shows_list_response.dart' as _i2;
import 'package:flutter_tv_shows/data/repositories/movies_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeShowsListResponse_0 extends _i1.Fake
    implements _i2.ShowsListResponse {}

/// A class which mocks [MoviesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviesRepository extends _i1.Mock implements _i3.MoviesRepository {
  MockMoviesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ShowsListResponse> getMovieList(int? page) =>
      (super.noSuchMethod(Invocation.method(#getMovieList, [page]),
              returnValue: Future<_i2.ShowsListResponse>.value(
                  _FakeShowsListResponse_0()))
          as _i4.Future<_i2.ShowsListResponse>);
}
